apiVersion: skaffold/v3
kind: Config

metadata:
  name: tobbo-api

manifests:
  rawYaml:
    - ./ops/k8s/*

build:
  artifacts:
    - image: "auth"
      context: ./auth
      docker:
        dockerfile: Dockerfile
        buildArgs:
          ENV: development
          POSTGRES_HOST: "{{ .POSTGRES_HOST }}"
          POSTGRES_DB: "{{ .POSTGRES_DB }}"
          POSTGRES_PASSWORD: "{{ .POSTGRES_PASSWORD }}"
          POSTGRES_PORT: "{{ .POSTGRES_PORT }}"
          POSTGRES_USER: "{{ .POSTGRES_USER }}"
          PORT: "{{ .PORT }}"

deploy:
  kubectl: {}
