apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: toboo-tls
spec:
  secretName: toboo-app
  commonName: api.to.boo
  dnsNames:
    - api.to.boo
  issuerRef:
    name: letsencrypt-cai
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cai
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "apps@to.boo"
    privateKeySecretRef:
      name: letsencrypt-toboo-private
    solvers:
      - http01:
          ingress:
            class: nginx
        selector: {}
