name: deploy-feature

on:
  pull_request:
    branches: [master]
env:
  DEPLOY_REVISION: "pr-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.sha }}"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{secrets.AWS_REGION }}
  AWS_ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
  AWS_EKS_CLUSTER: ${{ secrets.AWS_EKS_CLUSTER }}
  JWT_TOKEN_LONGEVITY: ${{ secrets.JWT_TOKEN_LONGEVITY }}
  JWT_KEY: ${{ secrets.JWT_KEY }}
  SENDGRID_USER_CREATED_MAIL_TEMPLATE_ID: ${{ secrets.SENDGRID_USER_CREATED_MAIL_TEMPLATE_ID }}
  SENDGRID_OTP_MAIL_TEMPLATE_ID: $${{ secrets.SENDGRID_OTP_MAIL_TEMPLATE_ID }}
  SENDGRID_USER_PASSWORD_UPDATED_TEMPLATE_ID: ${{ secrets.SENDGRID_USER_PASSWORD_UPDATED_TEMPLATE_ID }}
  PG_SECRET: ${{ secrets.PG_SECRET }}
  REDIS_HOST: ${{ secrets.REDIS_HOST }}
  REDIS_SECRET: ${{ secrets.REDIS_SECRET }}
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}

jobs:
  tests:
    uses: ./.github/workflows/test-feature.yaml
    secrets: inherit
  deploy:
    name: Deploy
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      # Install Node.js dependencies
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      # Install kubectl
      - name: Install kubectl
        run: |

          curl -LO https://dl.k8s.io/release/v1.28.3/bin/linux/amd64/kubectl
          curl -LO https://dl.k8s.io/release/v1.28.3/bin/linux/amd64/kubectl.sha256

          echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check

          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client

      # Install Skaffold
      - name: Install skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
          skaffold version
      # Cache skaffold image builds & config
      - name: Cache skaffold image builds & config
        uses: actions/cache@v2
        with:
          path: ~/.skaffold/
          key: fixed-${{ github.sha }}
        # Check AWS version and configure profile
      - name: Check AWS version
        run: |
          aws --version
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_REGION
          aws sts get-caller-identity

      #     #Connect to EKS cluster
      - name: Connect to EKS cluster
        run: aws eks --region $AWS_REGION update-kubeconfig --name $AWS_EKS_CLUSTER

        #Login to ECR registry
      - name: login-amazon-ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      #  Build and deploy
      - name: Build and then deploy to EKS cluster with Skaffold
        # Build and deploy to EKS cluster
        run: |
          skaffold run --default-repo ${{secrets.AWS_ECR_REGISTRY}}
      #
      # Verify deployment
      - name: verify deployment
        run: kubectl get pods
